ALTER TABLE students ADD COLUMN IF NOT EXISTS first_name VARCHAR(128);
ALTER TABLE students ADD COLUMN IF NOT EXISTS middle_name VARCHAR(128);
ALTER TABLE students ADD COLUMN IF NOT EXISTS last_name VARCHAR(128);
ALTER TABLE students ADD COLUMN IF NOT EXISTS father_occupation VARCHAR(255);
ALTER TABLE students ADD COLUMN IF NOT EXISTS mother_occupation VARCHAR(255);
ALTER TABLE students ADD COLUMN IF NOT EXISTS about_student TEXT;

ALTER TABLE teachers ADD COLUMN IF NOT EXISTS experience_summary TEXT;

ALTER TABLE parents ADD COLUMN IF NOT EXISTS occupation VARCHAR(255);
ALTER TABLE parents ADD COLUMN IF NOT EXISTS employer VARCHAR(255);
ALTER TABLE parents ADD COLUMN IF NOT EXISTS education_summary TEXT;
